//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{   
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices/", ConfigurationName="ServiceReference.CargaMasivaServicev4")]
    public interface CargaMasivaServicev4
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.cargaMasivaResponse> cargaMasivaAsync(ServiceReference.cargaMasiva request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.obtenerLocalidadesCorreoResponse> obtenerLocalidadesCorreoAsync(ServiceReference.obtenerLocalidadesCorreo request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices/")]
    public partial class dataParametro
    {
        
        private string claveField;
        
        private string valorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string clave
        {
            get
            {
                return this.claveField;
            }
            set
            {
                this.claveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string valor
        {
            get
            {
                return this.valorField;
            }
            set
            {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices/")]
    public partial class dataLocalidadesCorreo
    {
        
        private string ciudadField;
        
        private int codigoAHIVAField;
        
        private string codigoPostalField;
        
        private string departamentoField;
        
        private string direccionField;
        
        private int locCorreoBancField;
        
        private string nombreField;
        
        private string siteCodeField;
        
        private string telefonoField;
        
        private string unidadNegocioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ciudad
        {
            get
            {
                return this.ciudadField;
            }
            set
            {
                this.ciudadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoAHIVA
        {
            get
            {
                return this.codigoAHIVAField;
            }
            set
            {
                this.codigoAHIVAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigoPostal
        {
            get
            {
                return this.codigoPostalField;
            }
            set
            {
                this.codigoPostalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string departamento
        {
            get
            {
                return this.departamentoField;
            }
            set
            {
                this.departamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string direccion
        {
            get
            {
                return this.direccionField;
            }
            set
            {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int locCorreoBanc
        {
            get
            {
                return this.locCorreoBancField;
            }
            set
            {
                this.locCorreoBancField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string siteCode
        {
            get
            {
                return this.siteCodeField;
            }
            set
            {
                this.siteCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string telefono
        {
            get
            {
                return this.telefonoField;
            }
            set
            {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string unidadNegocio
        {
            get
            {
                return this.unidadNegocioField;
            }
            set
            {
                this.unidadNegocioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices/")]
    public partial class dataResponse
    {
        
        private int codigoRespuestaField;
        
        private string descripcionRespuestaField;
        
        private dataEnvio[] enviosField;
        
        private bool esErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoRespuesta
        {
            get
            {
                return this.codigoRespuestaField;
            }
            set
            {
                this.codigoRespuestaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcionRespuesta
        {
            get
            {
                return this.descripcionRespuestaField;
            }
            set
            {
                this.descripcionRespuestaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("envios", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public dataEnvio[] envios
        {
            get
            {
                return this.enviosField;
            }
            set
            {
                this.enviosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool esError
        {
            get
            {
                return this.esErrorField;
            }
            set
            {
                this.esErrorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices/")]
    public partial class dataEnvio
    {
        
        private string cedulaDestinatarioField;
        
        private string[] codigostrazabilidadField;
        
        private dataContraReembolso[] contraReembolsosField;
        
        private dataCostos costosField;
        
        private dataDevolucion datosdevolucionField;
        
        private dataDestinatario destinatarioField;
        
        private byte[] etiquetasGeneradasField;
        
        private dataFacturaConformada[] facturasConformadasField;
        
        private dataLugarEntrega lugarEntregaField;
        
        private dataPaquete[] paquetesSimplesField;
        
        private byte[] remitoField;
        
        private bool soloDestinatarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cedulaDestinatario
        {
            get
            {
                return this.cedulaDestinatarioField;
            }
            set
            {
                this.cedulaDestinatarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codigostrazabilidad", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string[] codigostrazabilidad
        {
            get
            {
                return this.codigostrazabilidadField;
            }
            set
            {
                this.codigostrazabilidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("contraReembolsos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public dataContraReembolso[] contraReembolsos
        {
            get
            {
                return this.contraReembolsosField;
            }
            set
            {
                this.contraReembolsosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public dataCostos costos
        {
            get
            {
                return this.costosField;
            }
            set
            {
                this.costosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public dataDevolucion datosdevolucion
        {
            get
            {
                return this.datosdevolucionField;
            }
            set
            {
                this.datosdevolucionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public dataDestinatario destinatario
        {
            get
            {
                return this.destinatarioField;
            }
            set
            {
                this.destinatarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=6)]
        public byte[] etiquetasGeneradas
        {
            get
            {
                return this.etiquetasGeneradasField;
            }
            set
            {
                this.etiquetasGeneradasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("facturasConformadas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public dataFacturaConformada[] facturasConformadas
        {
            get
            {
                return this.facturasConformadasField;
            }
            set
            {
                this.facturasConformadasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public dataLugarEntrega lugarEntrega
        {
            get
            {
                return this.lugarEntregaField;
            }
            set
            {
                this.lugarEntregaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("paquetesSimples", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public dataPaquete[] paquetesSimples
        {
            get
            {
                return this.paquetesSimplesField;
            }
            set
            {
                this.paquetesSimplesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=10)]
        public byte[] remito
        {
            get
            {
                return this.remitoField;
            }
            set
            {
                this.remitoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public bool soloDestinatario
        {
            get
            {
                return this.soloDestinatarioField;
            }
            set
            {
                this.soloDestinatarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices/")]
    public partial class dataContraReembolso
    {
        
        private double montoField;
        
        private string nroreferenciaField;
        
        private dataPaquete[] paquetesField;
        
        private string responsableServContraReembolsoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double monto
        {
            get
            {
                return this.montoField;
            }
            set
            {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nroreferencia
        {
            get
            {
                return this.nroreferenciaField;
            }
            set
            {
                this.nroreferenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("paquetes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public dataPaquete[] paquetes
        {
            get
            {
                return this.paquetesField;
            }
            set
            {
                this.paquetesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string responsableServContraReembolso
        {
            get
            {
                return this.responsableServContraReembolsoField;
            }
            set
            {
                this.responsableServContraReembolsoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices/")]
    public partial class dataPaquete
    {
        
        private int almacenamientoField;
        
        private bool almacenamientoFieldSpecified;
        
        private string codigoBarrasClienteField;
        
        private int empaqueField;
        
        private bool empaqueFieldSpecified;
        
        private bool garantiaplusField;
        
        private bool garantiaplusFieldSpecified;
        
        private int motivodevolucionField;
        
        private bool motivodevolucionFieldSpecified;
        
        private double pesoField;
        
        private string referenciaField;
        
        private string responsableServEntregaField;
        
        private double valordeclaradoField;
        
        private bool valordeclaradoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int almacenamiento
        {
            get
            {
                return this.almacenamientoField;
            }
            set
            {
                this.almacenamientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool almacenamientoSpecified
        {
            get
            {
                return this.almacenamientoFieldSpecified;
            }
            set
            {
                this.almacenamientoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigoBarrasCliente
        {
            get
            {
                return this.codigoBarrasClienteField;
            }
            set
            {
                this.codigoBarrasClienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int empaque
        {
            get
            {
                return this.empaqueField;
            }
            set
            {
                this.empaqueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool empaqueSpecified
        {
            get
            {
                return this.empaqueFieldSpecified;
            }
            set
            {
                this.empaqueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool garantiaplus
        {
            get
            {
                return this.garantiaplusField;
            }
            set
            {
                this.garantiaplusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool garantiaplusSpecified
        {
            get
            {
                return this.garantiaplusFieldSpecified;
            }
            set
            {
                this.garantiaplusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int motivodevolucion
        {
            get
            {
                return this.motivodevolucionField;
            }
            set
            {
                this.motivodevolucionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool motivodevolucionSpecified
        {
            get
            {
                return this.motivodevolucionFieldSpecified;
            }
            set
            {
                this.motivodevolucionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double peso
        {
            get
            {
                return this.pesoField;
            }
            set
            {
                this.pesoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string referencia
        {
            get
            {
                return this.referenciaField;
            }
            set
            {
                this.referenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string responsableServEntrega
        {
            get
            {
                return this.responsableServEntregaField;
            }
            set
            {
                this.responsableServEntregaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double valordeclarado
        {
            get
            {
                return this.valordeclaradoField;
            }
            set
            {
                this.valordeclaradoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valordeclaradoSpecified
        {
            get
            {
                return this.valordeclaradoFieldSpecified;
            }
            set
            {
                this.valordeclaradoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices/")]
    public partial class dataCostos
    {
        
        private int costoTotal_destinatarioField;
        
        private int costoTotal_remitenteField;
        
        private dataDetalleCostos detalleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int costoTotal_destinatario
        {
            get
            {
                return this.costoTotal_destinatarioField;
            }
            set
            {
                this.costoTotal_destinatarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int costoTotal_remitente
        {
            get
            {
                return this.costoTotal_remitenteField;
            }
            set
            {
                this.costoTotal_remitenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public dataDetalleCostos detalle
        {
            get
            {
                return this.detalleField;
            }
            set
            {
                this.detalleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices/")]
    public partial class dataDetalleCostos
    {
        
        private double costoAlmacenamiento_remitenteField;
        
        private double costoContrareembolso_destinatarioField;
        
        private double costoContrareembolso_remitenteField;
        
        private double costoEmpaque_remitenteField;
        
        private double costoFacturaConformada_destinatarioField;
        
        private double costoFacturaConformada_remitenteField;
        
        private double costoFarma_destinatarioField;
        
        private double costoFarma_remitenteField;
        
        private double costoMercaderia_destinatarioField;
        
        private double costoPrioritario_destinatarioField;
        
        private double costoPrioritario_remitenteField;
        
        private double costoRedondeo_destinatarioField;
        
        private double costoRedondeo_remitenteField;
        
        private double costoServEntrega_destinatarioField;
        
        private double costoServEntrega_remitenteField;
        
        private double costoTasa_destinatarioField;
        
        private double costoTasa_remitenteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double costoAlmacenamiento_remitente
        {
            get
            {
                return this.costoAlmacenamiento_remitenteField;
            }
            set
            {
                this.costoAlmacenamiento_remitenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double costoContrareembolso_destinatario
        {
            get
            {
                return this.costoContrareembolso_destinatarioField;
            }
            set
            {
                this.costoContrareembolso_destinatarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double costoContrareembolso_remitente
        {
            get
            {
                return this.costoContrareembolso_remitenteField;
            }
            set
            {
                this.costoContrareembolso_remitenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double costoEmpaque_remitente
        {
            get
            {
                return this.costoEmpaque_remitenteField;
            }
            set
            {
                this.costoEmpaque_remitenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double costoFacturaConformada_destinatario
        {
            get
            {
                return this.costoFacturaConformada_destinatarioField;
            }
            set
            {
                this.costoFacturaConformada_destinatarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double costoFacturaConformada_remitente
        {
            get
            {
                return this.costoFacturaConformada_remitenteField;
            }
            set
            {
                this.costoFacturaConformada_remitenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double costoFarma_destinatario
        {
            get
            {
                return this.costoFarma_destinatarioField;
            }
            set
            {
                this.costoFarma_destinatarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double costoFarma_remitente
        {
            get
            {
                return this.costoFarma_remitenteField;
            }
            set
            {
                this.costoFarma_remitenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double costoMercaderia_destinatario
        {
            get
            {
                return this.costoMercaderia_destinatarioField;
            }
            set
            {
                this.costoMercaderia_destinatarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public double costoPrioritario_destinatario
        {
            get
            {
                return this.costoPrioritario_destinatarioField;
            }
            set
            {
                this.costoPrioritario_destinatarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public double costoPrioritario_remitente
        {
            get
            {
                return this.costoPrioritario_remitenteField;
            }
            set
            {
                this.costoPrioritario_remitenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public double costoRedondeo_destinatario
        {
            get
            {
                return this.costoRedondeo_destinatarioField;
            }
            set
            {
                this.costoRedondeo_destinatarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public double costoRedondeo_remitente
        {
            get
            {
                return this.costoRedondeo_remitenteField;
            }
            set
            {
                this.costoRedondeo_remitenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public double costoServEntrega_destinatario
        {
            get
            {
                return this.costoServEntrega_destinatarioField;
            }
            set
            {
                this.costoServEntrega_destinatarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public double costoServEntrega_remitente
        {
            get
            {
                return this.costoServEntrega_remitenteField;
            }
            set
            {
                this.costoServEntrega_remitenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public double costoTasa_destinatario
        {
            get
            {
                return this.costoTasa_destinatarioField;
            }
            set
            {
                this.costoTasa_destinatarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public double costoTasa_remitente
        {
            get
            {
                return this.costoTasa_remitenteField;
            }
            set
            {
                this.costoTasa_remitenteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices/")]
    public partial class dataDevolucion
    {
        
        private string calleField;
        
        private string departamentoField;
        
        private string localidadField;
        
        private string manzanaField;
        
        private string nroAptoField;
        
        private string nroPuertaField;
        
        private string observacionesDireccionField;
        
        private string oficinaCorreoField;
        
        private string solarField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string calle
        {
            get
            {
                return this.calleField;
            }
            set
            {
                this.calleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string departamento
        {
            get
            {
                return this.departamentoField;
            }
            set
            {
                this.departamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string localidad
        {
            get
            {
                return this.localidadField;
            }
            set
            {
                this.localidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string manzana
        {
            get
            {
                return this.manzanaField;
            }
            set
            {
                this.manzanaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nroApto
        {
            get
            {
                return this.nroAptoField;
            }
            set
            {
                this.nroAptoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nroPuerta
        {
            get
            {
                return this.nroPuertaField;
            }
            set
            {
                this.nroPuertaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string observacionesDireccion
        {
            get
            {
                return this.observacionesDireccionField;
            }
            set
            {
                this.observacionesDireccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string oficinaCorreo
        {
            get
            {
                return this.oficinaCorreoField;
            }
            set
            {
                this.oficinaCorreoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string solar
        {
            get
            {
                return this.solarField;
            }
            set
            {
                this.solarField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices/")]
    public partial class dataDestinatario
    {
        
        private string celularField;
        
        private string mailField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string celular
        {
            get
            {
                return this.celularField;
            }
            set
            {
                this.celularField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mail
        {
            get
            {
                return this.mailField;
            }
            set
            {
                this.mailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices/")]
    public partial class dataFacturaConformada
    {
        
        private string nroreferenciaField;
        
        private dataPaquete[] paquetesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nroreferencia
        {
            get
            {
                return this.nroreferenciaField;
            }
            set
            {
                this.nroreferenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("paquetes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public dataPaquete[] paquetes
        {
            get
            {
                return this.paquetesField;
            }
            set
            {
                this.paquetesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices/")]
    public partial class dataLugarEntrega
    {
        
        private string calleField;
        
        private string departamentoField;
        
        private string localidadField;
        
        private string manzanaField;
        
        private string nroAptoField;
        
        private string nroPuertaField;
        
        private string observacionesDireccionField;
        
        private string oficinaCorreoField;
        
        private string solarField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string calle
        {
            get
            {
                return this.calleField;
            }
            set
            {
                this.calleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string departamento
        {
            get
            {
                return this.departamentoField;
            }
            set
            {
                this.departamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string localidad
        {
            get
            {
                return this.localidadField;
            }
            set
            {
                this.localidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string manzana
        {
            get
            {
                return this.manzanaField;
            }
            set
            {
                this.manzanaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nroApto
        {
            get
            {
                return this.nroAptoField;
            }
            set
            {
                this.nroAptoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nroPuerta
        {
            get
            {
                return this.nroPuertaField;
            }
            set
            {
                this.nroPuertaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string observacionesDireccion
        {
            get
            {
                return this.observacionesDireccionField;
            }
            set
            {
                this.observacionesDireccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string oficinaCorreo
        {
            get
            {
                return this.oficinaCorreoField;
            }
            set
            {
                this.oficinaCorreoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string solar
        {
            get
            {
                return this.solarField;
            }
            set
            {
                this.solarField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices/")]
    public partial class dataRetiro
    {
        
        private string contactoField;
        
        private int desdeField;
        
        private string direccionField;
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private int hastaField;
        
        private string mailField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string contacto
        {
            get
            {
                return this.contactoField;
            }
            set
            {
                this.contactoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int desde
        {
            get
            {
                return this.desdeField;
            }
            set
            {
                this.desdeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string direccion
        {
            get
            {
                return this.direccionField;
            }
            set
            {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified
        {
            get
            {
                return this.fechaFieldSpecified;
            }
            set
            {
                this.fechaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int hasta
        {
            get
            {
                return this.hastaField;
            }
            set
            {
                this.hastaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string mail
        {
            get
            {
                return this.mailField;
            }
            set
            {
                this.mailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string telefono
        {
            get
            {
                return this.telefonoField;
            }
            set
            {
                this.telefonoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cargaMasiva", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class cargaMasiva
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("arg4", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.dataParametro[] arg4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("arg5", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.dataEnvio[] arg5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.dataRetiro arg6;
        
        public cargaMasiva()
        {
        }
        
        public cargaMasiva(string arg0, string arg1, string arg2, string arg3, ServiceReference.dataParametro[] arg4, ServiceReference.dataEnvio[] arg5, ServiceReference.dataRetiro arg6)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
            this.arg6 = arg6;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cargaMasivaResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class cargaMasivaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.dataResponse @return;
        
        public cargaMasivaResponse()
        {
        }
        
        public cargaMasivaResponse(ServiceReference.dataResponse @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerLocalidadesCorreo", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class obtenerLocalidadesCorreo
    {
        
        public obtenerLocalidadesCorreo()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerLocalidadesCorreoResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class obtenerLocalidadesCorreoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.dataLocalidadesCorreo[] @return;
        
        public obtenerLocalidadesCorreoResponse()
        {
        }
        
        public obtenerLocalidadesCorreoResponse(ServiceReference.dataLocalidadesCorreo[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface CargaMasivaServicev4Channel : ServiceReference.CargaMasivaServicev4, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class CargaMasivaServicev4Client : System.ServiceModel.ClientBase<ServiceReference.CargaMasivaServicev4>, ServiceReference.CargaMasivaServicev4
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CargaMasivaServicev4Client() : 
                base(CargaMasivaServicev4Client.GetDefaultBinding(), CargaMasivaServicev4Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CargaMasivaServicev4Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CargaMasivaServicev4Client(EndpointConfiguration endpointConfiguration) : 
                base(CargaMasivaServicev4Client.GetBindingForEndpoint(endpointConfiguration), CargaMasivaServicev4Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CargaMasivaServicev4Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CargaMasivaServicev4Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CargaMasivaServicev4Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CargaMasivaServicev4Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CargaMasivaServicev4Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.cargaMasivaResponse> ServiceReference.CargaMasivaServicev4.cargaMasivaAsync(ServiceReference.cargaMasiva request)
        {
            return base.Channel.cargaMasivaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.cargaMasivaResponse> cargaMasivaAsync(string arg0, string arg1, string arg2, string arg3, ServiceReference.dataParametro[] arg4, ServiceReference.dataEnvio[] arg5, ServiceReference.dataRetiro arg6)
        {
            ServiceReference.cargaMasiva inValue = new ServiceReference.cargaMasiva();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            inValue.arg6 = arg6;
            return ((ServiceReference.CargaMasivaServicev4)(this)).cargaMasivaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.obtenerLocalidadesCorreoResponse> ServiceReference.CargaMasivaServicev4.obtenerLocalidadesCorreoAsync(ServiceReference.obtenerLocalidadesCorreo request)
        {
            return base.Channel.obtenerLocalidadesCorreoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.obtenerLocalidadesCorreoResponse> obtenerLocalidadesCorreoAsync()
        {
            ServiceReference.obtenerLocalidadesCorreo inValue = new ServiceReference.obtenerLocalidadesCorreo();
            return ((ServiceReference.CargaMasivaServicev4)(this)).obtenerLocalidadesCorreoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CargaMasivaServicev4Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CargaMasivaServicev4Port))
            {
                return new System.ServiceModel.EndpointAddress("http://ahivatest.correo.com.uy/web/CargaMasivaServicev4");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CargaMasivaServicev4Client.GetBindingForEndpoint(EndpointConfiguration.CargaMasivaServicev4Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CargaMasivaServicev4Client.GetEndpointAddress(EndpointConfiguration.CargaMasivaServicev4Port);
        }
        
        public enum EndpointConfiguration
        {
            
            CargaMasivaServicev4Port,
        }
    }
}
